#  Builds a Eureka Server "prototype" instance. I'm going to create an AMI from this, manually (for now)

- hosts: localhost
  gather_facts: no
  vars: 
     region: us-east-2
     keypair_name: lit-backend-keypair
     security_group_name: eureka-server-security-group
     instance_type: t2.nano
     image_name: ami-8a7859ef

  tasks:
    - name: Setup Global Vars
      set_fact:
        region: "{{ region }}"
    - name: Setup security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: Security rules for Eureka Server
        region: "{{ region }}"
        rules_egress:
            - proto: tcp
              from_port: 0
              to_port: 65535
              cidr_ip: 0.0.0.0/0
        rules:
           - proto: tcp
             from_port: 8761
             to_port: 8761
             cidr_ip: 0.0.0.0/0

           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0

    - name: Provision an instance
      ec2:
        key_name: "{{ keypair_name }}"
        group: "{{ security_group_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image_name }}"
        wait: true
        region: "{{region}}"
        exact_count: 1 
        count_tag:
          Name: Eureka_Server
          Deploy: New
        instance_tags:
          Name: Eureka_Server
          Deploy: Blue
        instance_profile_name: eureka-eip-reallocation
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ec2.instances}}"

    - name: Wait for SSH Server to start responding
      wait_for:
              port: 22
              host: "{{item.public_ip}}"
              state: started
      with_items: "{{ec2.instances}}"

- hosts: tag_Name_Eureka_Server ec2hosts
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
    become: true
  
  - name: Install JDK
    yum:
       name: java-1.8.0-openjdk-devel
       state: latest
    become: true

  - name: Use Java8 for Runtime Java
    alternatives:
       name: java
       path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
       link: /usr/bin/java
    become: true

  - name: Send the deployment across to the new instance
    copy: 
       src: target/DiscoveryService-0.0.1-SNAPSHOT.jar
       dest: /home/ec2-user/app/target/
       mode: 0700

  - name: Build a link to the executable so it becomes a service
    file:
            src: /home/ec2-user/app/target/DiscoveryService-0.0.1-SNAPSHOT.jar
            dest: /etc/init.d/discovery-service
            state: link
    become: true

  - name: Install microservice as a startup service
    service:
            name: discovery-service
            state: started
            enabled: yes
    become: true

  - name: Wait for the new webserver to begin responding
    wait_for:
            host: localhost
            port: 8761
            state: started

# Series of steps to implement a Green -> Blue switchover

- hosts: localhost
  tasks:
  - name: Gather facts about the new blue server
    ec2_remote_facts:
       filters:
          "tag:Deploy": Blue
          "tag:Name": ConfigServer
          instance-state-name: running
       region: "{{ region }}"
    register: new_server

  - name: Get the id of the old, soon to be dead, green server
    ec2_remote_facts:
       filters:
          "tag:Deploy": Green
          "tag:Name": ConfigServer
          instance-state-name: running
       region: "{{ region }}"
    register: old_green

  - name: Terminate the existing Green Server.
    ec2:
      exact_count: 0
      count_tag:
        Deploy: Green
        Name: ConfigServer
      region: "{{ region }}"
      image: notneeded

  - name: All done, set new server to Green status
    ec2_tag:
       region: "{{ region }}"
       resource: "{{ new_server.instances[0].id }}"
       tags:
          Deploy: Green
       state: present

  - name: Remove Blue Tag
    ec2_tag:
       region: "{{ region }}"
       resource: "{{ new_server.instances[0].id }}"
       tags:
          Deploy: Blue
       state: absent
