server:
  port: 8761
  
eureka:
  client:
    region: us-east-2
    serviceUrl:
      defaultZone: http://ec2-13-58-181-207.us-east-2.compute.amazonaws.com:${server.port}/eureka
  server:
    enableSelfPreservation: false
    renewalPercentThreshold: 0.1
    
---
   
spring:
  profiles: dev
server:
  port: 8761
  
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    