server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
    
---
   
spring:
  profiles: dev
server:
  port: 8761