server:
  port: 8761
  
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
  
eureka:
  datacenter: cloud
  client:
    region: us-east-2
    serviceUrl:
      defaultZone: http://ec2-13-59-80-6.us-east-2.compute.amazonaws.com:8761/eureka/
  server:
    enableSelfPreservation: false
    renewalPercentThreshold: 0.1
    
    
management:
  contextPath: /mgmt
  security:
    enabled: false
    
endpoints:
  enabled: false
  health.enabled: true
  info.enabled: true
  logfile.enabled: true
  loggers.enabled: true
  metrics.enabled: true
  trace.enabled: true
  
    
---
   
spring:
  profiles: dev
server:
  port: 8761
  
security:
  basic:
    enabled: false
  
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    